services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    environment:
      FLASK_MAIL_SERVER: mailpit
      FLASK_MAIL_PORT: 1025
      # FLASK_DRAMATIQ_BROKER_URL: redis://valkey:6379/0

  mailpit: # email testing tool
    image: axllent/mailpit

  # uncomment if you need redis (for queueing, caching, etc.)
  #
  # valkey:
  #   image: valkey/valkey

